[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
benimator = "4.1.3"
bevy = { version = "0.12", features = ["dynamic_linking"] }
bevy_egui = "0.24.0"
bevy_quinnet = "0.6.0"
bevy_rapier2d = "0.24.0"
leafwing-input-manager = "0.12"
quinn = "0.10.1"
shared = { path = "../shared" }
