[package]
name = "game_grid_builder"
version = "0.1.0"
edition = "2024"
resolver = "2"

[features]
dynamic_linking = ["bevy/dynamic_linking"]

[dependencies]
tool_physics = { path = "../tool_physics" }
tools = { path = "../tools" }

[dependencies.bevy]
version = "0.14.2"
default-features = false
features = [
    "animation",
    "bevy_asset",
    "bevy_audio",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_dev_tools",
    "bevy_gilrs",
    "bevy_gizmos",
    "bevy_gltf",
    "bevy_pbr",
    "bevy_render",
    "bevy_scene",
    "bevy_sprite",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
    "default_font",
    "hdr",
    "multi_threaded",
    "png",
    "smaa_luts",
    "sysinfo_plugin",
    "tonemapping_luts",
    "vorbis",
    "wayland",
    "file_watcher"
]
