name: Release

on:
  push:
    branches: [ space_game ]
  pull_request:
    branches: [ space_game ]

env:
  CARGO_TERM_COLOR: always
  # update with the name of the main binary
  binary: game_space

permissions:
  contents: write

jobs:
  # Build for Linux
  release-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: ${{ env.use_git_lfs }}

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-release-linux-${{ hashFiles('**/Cargo.toml') }}

      - name: Install Dependencies
        run: |
          sudo apt-get update; sudo apt-get -y install pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libwayland-dev libxkbcommon-dev mold clang

      - name: Build
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu --bin game_space

      - name: Prepare package
        run: |
          mkdir linux
          cp target/x86_64-unknown-linux-gnu/release/${{ env.binary }} linux/
          cp -r assets linux/ || true # Try to copy, but ignore if it can't copy if source directory does not exist

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v4
        with:
          path: linux/*
          name: linux
          retention-days: 1

  # Build for Windows
  release-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: ${{ env.use_git_lfs }}

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-release-windows-${{ hashFiles('**/Cargo.toml') }}

      - name: Build
        run: |
          cargo build --release --target x86_64-pc-windows-msvc --bin game_space

      - name: Prepare package
        run: |
          mkdir windows
          cp target/x86_64-pc-windows-msvc/release/${{ env.binary }}.exe windows/
          mkdir assets -ea 0 # create the assets directory if it does not exist, it will get ignored in the zip if empty
          cp -r assets windows/

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v4
        with:
          path: windows/*
          name: windows
          retention-days: 1